[package]
name = "rust-tests"
version = "0.0.0"
rust-version = "1.89"
edition = "2024"
publish = false

[[bin]]
name = "visual"
path = "src/visual.rs"

[dependencies]
fastLoess = { path = "../../crates/fastLoess" }

[dev-dependencies]
loess-rs = { path = "../../crates/loess-rs", features = ["dev"] }
