/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Batch LOESS smoothing. */
export declare class Loess {
  /** Create a new batch LOESS smoother. */
  constructor(options?: SmoothOptions | undefined | null)
  /** Fit the model. */
  fit(x: Float64Array, y: Float64Array, customWeights?: Float64Array | undefined | null): LoessResult
  /** Fit the model asynchronously. */
  fit_async(x: Float64Array, y: Float64Array, customWeights?: Float64Array | undefined | null): Promise<unknown>
}

/** Result of a LOESS fit. */
export declare class LoessResult {
  /** Get the sorted x values. */
  get x(): Float64Array
  /** Get the smoothed y values. */
  get y(): Float64Array
  /** Get residuals (if requested). */
  get residuals(): Float64Array | null
  /** Get standard errors (if requested/computed). */
  get standard_errors(): Float64Array | null
  /** Get lower confidence bounds (if requested). */
  get confidence_lower(): Float64Array | null
  /** Get upper confidence bounds (if requested). */
  get confidence_upper(): Float64Array | null
  /** Get lower prediction bounds (if requested). */
  get prediction_lower(): Float64Array | null
  /** Get upper prediction bounds (if requested). */
  get prediction_upper(): Float64Array | null
  /** Get robustness weights (if requested). */
  get robustness_weights(): Float64Array | null
  /** Get diagnostics (if requested). */
  get diagnostics(): Diagnostics | null
  /** Get cross-validation scores (if CV was performed). */
  get cv_scores(): Float64Array | null
  /** Get the fraction used for smoothing. */
  get fraction_used(): number
  /** Get the number of iterations performed. */
  get iterations_used(): number | null
  /** Get equivalent number of parameters (hat-matrix stat, if return_se was set). */
  get enp(): number | null
  /** Get trace of hat matrix (if return_se was set). */
  get trace_hat(): number | null
  /** Get first delta statistic (if return_se was set). */
  get delta1(): number | null
  /** Get second delta statistic (if return_se was set). */
  get delta2(): number | null
  /** Get residual scale estimate (if return_se was set). */
  get residual_scale(): number | null
  /** Get per-point leverage / hat-matrix diagonal (if return_se was set). */
  get leverage(): Float64Array | null
  /** Get number of predictor dimensions. */
  get dimensions(): number
}

/** Online LOESS smoother for real-time data. */
export declare class OnlineLoess {
  /** Create a new online LOESS smoother. */
  constructor(options?: SmoothOptions | undefined | null, onlineOpts?: OnlineOptions | undefined | null)
  /** Add a single point and get the smoothed value if enough points are available. */
  add_point(x: number, y: number): OnlineOutput | null
}

/** Streaming LOESS smoother for large datasets. */
export declare class StreamingLoess {
  /** Create a new streaming LOESS smoother. */
  constructor(options?: SmoothOptions | undefined | null, streamingOpts?: StreamingOptions | undefined | null)
  /** Process a chunk of data. */
  process_chunk(x: Float64Array, y: Float64Array): LoessResult
  /** Finalize the stream and return remaining data. */
  finalize(): LoessResult
}

/** Diagnostic statistics for the LOESS fit. */
export interface Diagnostics {
  /** Root Mean Squared Error. */
  rmse: number
  /** Mean Absolute Error. */
  mae: number
  /** R-squared (coefficient of determination). */
  r_squared: number
  /** Akaike Information Criterion (if computed). */
  aic?: number
  /** Corrected AIC (if computed). */
  aicc?: number
  /** Effective degrees of freedom (if computed). */
  effective_df?: number
  /** Residual standard deviation. */
  residual_sd: number
}

/** Configuration options for online processing. */
export interface OnlineOptions {
  /** Maximum number of points to keep in the window. Default: 1000. */
  window_capacity?: number
  /** Minimum points required before smoothing starts. Default: 3. */
  min_points?: number
  /** Update mode ("full", "incremental"). Default: "full". */
  update_mode?: string
}

/** Result of a single online update step. */
export interface OnlineOutput {
  /** Smoothed value for the latest point. */
  smoothed: number
  /** Standard error (if computed). */
  std_error?: number
  /** Residual y − smoothed (if computed). */
  residual?: number
  /** Robustness weight for the latest point (if computed). */
  robustness_weight?: number
  /** Number of robustness iterations performed (if applicable). */
  iterations_used?: number
}

/** Configuration options for LOESS smoothing. */
export interface SmoothOptions {
  /** Smoothing fraction (0 < fraction <= 1). Default: 0.67. */
  fraction?: number
  /** Number of robustness iterations. Default: 3. */
  iterations?: number
  /** Weight function ("tricube", "epanechnikov", "gaussian", "uniform", "biweight", "triangle", "cosine"). Default: "tricube". */
  weight_function?: string
  /** Robustness method ("bisquare", "huber", "talwar"). Default: "bisquare". */
  robustness_method?: string
  /** Fallback strategy when weights are zero ("use_local_mean", "return_original", "return_none"). Default: "use_local_mean". */
  zero_weight_fallback?: string
  /** Boundary handling ("extend", "reflect", "zero", "noboundary"). Default: "extend". */
  boundary_policy?: string
  /** Scaling method ("mad", "mar", "mean"). Default: "mad". */
  scaling_method?: string
  /** Auto-convergence tolerance. Default: None. */
  auto_converge?: number
  /** Return residuals in result. Default: false. */
  return_residuals?: boolean
  /** Return robustness weights in result. Default: false. */
  return_robustness_weights?: boolean
  /** Return diagnostics (RMSE, etc.). Default: false. */
  return_diagnostics?: boolean
  /** Calculate confidence intervals (e.g., 0.95). Default: None. */
  confidence_intervals?: number
  /** Calculate prediction intervals. Default: None. */
  prediction_intervals?: number
  /** Fractions to use for cross-validation. */
  cv_fractions?: Array<number>
  /** CV method ("loocv", "kfold"). Default: "kfold". */
  cv_method?: string
  /** Number of folds for K-Fold CV. Default: 5. */
  cv_k?: number
  /** Enable parallel execution. Default: true. */
  parallel?: boolean
  /** Polynomial degree ("constant", "linear", "quadratic", etc.). Default: "linear". */
  degree?: string
  /** Number of predictor dimensions. Default: 1. */
  dimensions?: number
  /** Distance metric ("normalized", "euclidean", "manhattan", "chebyshev", "minkowski:p", "weighted"). Default: "normalized". */
  distance_metric?: string
  /** Per-dimension weights for the "weighted" distance metric. */
  weighted_metric_weights?: Array<number>
  /** Surface mode ("interpolation" or "direct"). Default: "interpolation". */
  surface_mode?: string
  /** Compute hat-matrix statistics (enp, trace_hat, etc.). Default: false. */
  return_se?: boolean
  /** Interpolation cell size (default 0.2). Smaller = more vertices, higher accuracy. */
  cell?: number
  /** Maximum number of interpolation vertices. */
  interpolation_vertices?: number
  /** Reduce polynomial degree to linear at boundary vertices (default true). */
  boundary_degree_fallback?: boolean
  /** Random seed for reproducible K-fold cross-validation splits. */
  cv_seed?: number
}

/** Configuration options for streaming processing. */
export interface StreamingOptions {
  /** Size of each data chunk. Default: 5000. */
  chunk_size?: number
  /** Header/footer overlap size. Default: chunk_size / 10, min. 1. */
  overlap?: number
  /** Strategy for merging chunk overlaps ("average", "weighted_average", "take_first", "take_last"). */
  merge_strategy?: string
}
