/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class LoessResultObj {
  get x(): Float64Array
  get y(): Float64Array
  get residuals(): Float64Array | null
  get standardErrors(): Float64Array | null
  get confidenceLower(): Float64Array | null
  get confidenceUpper(): Float64Array | null
  get predictionLower(): Float64Array | null
  get predictionUpper(): Float64Array | null
  get robustnessWeights(): Float64Array | null
  get diagnostics(): Diagnostics | null
  get cvScores(): Float64Array | null
  get fractionUsed(): number
  get iterationsUsed(): number | null
}

export declare class OnlineLoess {
  constructor(options?: SmoothOptions | undefined | null, onlineOpts?: OnlineOptions | undefined | null)
  update(x: number, y: number): number | null
}

export declare class StreamingLoess {
  constructor(options?: SmoothOptions | undefined | null, streamingOpts?: StreamingOptions | undefined | null)
  processChunk(x: Float64Array, y: Float64Array): LoessResultObj
  finalize(): LoessResultObj
}

export interface Diagnostics {
  rmse: number
  mae: number
  rSquared: number
  aic?: number
  aicc?: number
  effectiveDf?: number
  residualSd: number
}

export interface OnlineOptions {
  windowCapacity?: number
  minPoints?: number
  updateMode?: string
}

export declare function smooth(x: Float64Array, y: Float64Array, options?: SmoothOptions | undefined | null): LoessResultObj

export interface SmoothOptions {
  fraction?: number
  iterations?: number
  delta?: number
  weightFunction?: string
  robustnessMethod?: string
  zeroWeightFallback?: string
  boundaryPolicy?: string
  scalingMethod?: string
  autoConverge?: number
  returnResiduals?: boolean
  returnRobustnessWeights?: boolean
  returnDiagnostics?: boolean
  confidenceIntervals?: number
  predictionIntervals?: number
  cvFractions?: Array<number>
  cvMethod?: string
  cvK?: number
  parallel?: boolean
}

export interface StreamingOptions {
  chunkSize?: number
  overlap?: number
  mergeStrategy?: string
}
