// Generated by extendr: do not edit by hand

#include <R.h>
#include <Rinternals.h>

extern void R_init_rfastloess_extendr(DllInfo *dll);

void R_init_rfastloess(DllInfo *dll) {
    R_init_rfastloess_extendr(dll);
}
