var searchData=
[
  ['dashboard_20example_0',['Real-Time Dashboard Example',['../md_docs_2use-case-real-time.html#autotoc_md316',1,'']]],
  ['data_1',['data',['../md_docs_2use-case-genomics.html#autotoc_md304',1,'Best Practices for Genomic Data'],['../md_docs_2dimensions.html#autotoc_md136',1,'Distance Metrics for Multivariate Data'],['../md_docs_2use-case-time-series.html#autotoc_md334',1,'Handling Missing Data']]],
  ['data_20example_2',['Sensor Data Example',['../md_docs_2use-case-real-time.html#autotoc_md311',1,'']]],
  ['data_20smoothing_3',['Genomic Data Smoothing',['../md_docs_2use-case-genomics.html',1,'']]],
  ['decision_20guide_4',['Quick Decision Guide',['../index.html#autotoc_md74',1,'']]],
  ['default_5',['default',['../md_docs_2dimensions.html#autotoc_md130',1,'1D — Standard (Default)'],['../md_docs_2robustness.html#autotoc_md269',1,'Bisquare (Default)'],['../md_docs_2degree.html#autotoc_md114',1,'Degree 1 — Local Linear (Default)'],['../md_docs_2boundary.html#autotoc_md52',1,'Extend (Default)'],['../md_docs_2scaling.html#autotoc_md285',1,'MAD — Median Absolute Deviation (Default)'],['../md_docs_2kernels.html#autotoc_md164',1,'Tricube (Default)']]],
  ['degree_6',['degree',['../md_docs_2degree.html#autotoc_md122',1,'Choosing the Right Degree'],['../md_docs_2api.html#autotoc_md39',1,'degree'],['../md_docs_2parameters.html#autotoc_md201',1,'degree'],['../md_docs_2degree.html',1,'Polynomial Degree']]],
  ['degree_200_20—_20local_20constant_7',['Degree 0 — Local Constant',['../md_docs_2degree.html#autotoc_md112',1,'']]],
  ['degree_201_20—_20local_20linear_20default_8',['Degree 1 — Local Linear (Default)',['../md_docs_2degree.html#autotoc_md114',1,'']]],
  ['degree_202_20—_20local_20quadratic_9',['Degree 2 — Local Quadratic',['../md_docs_2degree.html#autotoc_md116',1,'']]],
  ['degree_203_20—_20local_20cubic_10',['Degree 3 — Local Cubic',['../md_docs_2degree.html#autotoc_md118',1,'']]],
  ['degree_204_20—_20local_20quartic_11',['Degree 4 — Local Quartic',['../md_docs_2degree.html#autotoc_md120',1,'']]],
  ['degree_20effects_12',['Higher Degree Effects',['../md_docs_2degree.html#autotoc_md124',1,'']]],
  ['degree_2emd_13',['degree.md',['../degree_8md.html',1,'']]],
  ['detecting_20outliers_14',['Detecting Outliers',['../md_docs_2robustness.html#autotoc_md277',1,'']]],
  ['detrending_15',['Detrending',['../md_docs_2use-case-time-series.html#autotoc_md330',1,'']]],
  ['deviation_20default_16',['MAD — Median Absolute Deviation (Default)',['../md_docs_2scaling.html#autotoc_md285',1,'']]],
  ['dimensions_17',['dimensions',['../md_docs_2parameters.html#autotoc_md209',1,'']]],
  ['dimensions_2emd_18',['dimensions.md',['../dimensions_8md.html',1,'']]],
  ['distance_20metrics_20for_20multivariate_20data_19',['Distance Metrics for Multivariate Data',['../md_docs_2dimensions.html#autotoc_md136',1,'']]],
  ['distance_5fmetric_20',['distance_metric',['../md_docs_2api.html#autotoc_md40',1,'']]],
  ['distance_5fmetric_20weighted_5fmetric_5fweights_21',['distance_metric / weighted_metric_weights',['../md_docs_2parameters.html#autotoc_md211',1,'']]]
];
