var searchData=
[
  ['a_20kernel_0',['Choosing a Kernel',['../md_docs_2kernels.html#autotoc_md164',1,'']]],
  ['a_20policy_1',['Choosing a Policy',['../md_docs_2boundary.html#autotoc_md60',1,'']]],
  ['a_20scaling_20method_2',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md283',1,'']]],
  ['a_20strategy_3',['Choosing a Strategy',['../md_docs_2merge.html#autotoc_md176',1,'']]],
  ['absolute_20deviation_20default_4',['MAD — Median Absolute Deviation (Default)',['../md_docs_2scaling.html#autotoc_md277',1,'']]],
  ['absolute_20residual_5',['absolute residual',['../md_docs_2scaling.html#autotoc_md279',1,'MAR — Median Absolute Residual'],['../md_docs_2scaling.html#autotoc_md281',1,'Mean — Mean Absolute Residual']]],
  ['adapter_6',['adapter',['../md_docs_2batch.html',1,'Batch Adapter'],['../md_docs_2online.html',1,'Online Adapter'],['../md_docs_2streaming.html',1,'Streaming Adapter']]],
  ['adapter_20choice_7',['adapter-choice',['../md_docs_2adapter-choice.html',1,'']]],
  ['adapter_20parameters_8',['Adapter Parameters',['../md_docs_2parameters.html#autotoc_md235',1,'']]],
  ['adapter_2dchoice_2emd_9',['adapter-choice.md',['../adapter-choice_8md.html',1,'']]],
  ['advantages_10',['Key Advantages',['../index.html#autotoc_md74',1,'']]],
  ['also_11',['also',['../md_docs_2use-case-time-series.html#autotoc_md340',1,'See Also'],['../md_docs_2use-case-genomics.html#autotoc_md304',1,'See Also'],['../md_docs_2use-case-real-time.html#autotoc_md322',1,'See Also']]],
  ['analysis_12',['analysis',['../md_docs_2use-case-time-series.html#autotoc_md334',1,'Multi-Scale Analysis'],['../md_docs_2use-case-time-series.html#autotoc_md323',1,'Time Series Analysis']]],
  ['and_20higher_13',['3D and Higher',['../md_docs_2dimensions.html#autotoc_md120',1,'']]],
  ['api_20reference_14',['api reference',['../md_docs_2api.html',1,'fastLoess C++ API Reference'],['../md_docs_2api-online.html',1,'OnlineLoess — C++ API Reference'],['../md_docs_2api-streaming.html',1,'StreamingLoess — C++ API Reference']]],
  ['api_2donline_2emd_15',['api-online.md',['../api-online_8md.html',1,'']]],
  ['api_2dstreaming_2emd_16',['api-streaming.md',['../api-streaming_8md.html',1,'']]],
  ['api_2emd_17',['api.md',['../api_8md.html',1,'']]],
  ['application_18',['Application',['../md_docs_2use-case-genomics.html#autotoc_md298',1,'']]],
  ['auto_20convergence_19',['Auto-Convergence',['../md_docs_2robustness.html#autotoc_md273',1,'']]],
  ['auto_5fconverge_20',['auto_converge',['../md_docs_2parameters.html#autotoc_md217',1,'']]],
  ['availability_21',['availability',['../md_docs_2cross-validation.html#autotoc_md92',1,'Availability'],['../md_docs_2intervals.html#autotoc_md144',1,'Availability']]],
  ['available_20kernels_22',['Available Kernels',['../md_docs_2kernels.html#autotoc_md148',1,'']]],
  ['average_23',['average',['../md_docs_2merge.html#autotoc_md168',1,'Average'],['../md_docs_2merge.html#autotoc_md174',1,'Weighted Average']]]
];
