var searchData=
[
  ['scale_20analysis_0',['Multi-Scale Analysis',['../md_docs_2use-case-time-series.html#autotoc_md336',1,'']]],
  ['scale_20estimation_1',['Scale Estimation',['../md_docs_2robustness.html#autotoc_md279',1,'']]],
  ['scaling_20method_2',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md291',1,'']]],
  ['scaling_20methods_3',['Scaling Methods',['../md_docs_2scaling.html',1,'']]],
  ['scaling_2emd_4',['scaling.md',['../scaling_8md.html',1,'']]],
  ['scaling_5fmethod_5',['scaling_method',['../md_docs_2parameters.html#autotoc_md221',1,'scaling_method'],['../md_docs_2api.html#autotoc_md37',1,'scaling_method']]],
  ['see_20also_6',['see also',['../md_docs_2use-case-time-series.html#autotoc_md342',1,'See Also'],['../md_docs_2custom-weights.html#autotoc_md108',1,'See Also'],['../md_docs_2use-case-genomics.html#autotoc_md306',1,'See Also'],['../md_docs_2use-case-real-time.html#autotoc_md324',1,'See Also']]],
  ['seeded_20randomization_7',['Seeded Randomization',['../md_docs_2cross-validation.html#autotoc_md86',1,'']]],
  ['sensor_20data_20example_8',['Sensor Data Example',['../md_docs_2use-case-real-time.html#autotoc_md311',1,'']]],
  ['seq_20signal_20smoothing_9',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md299',1,'']]],
  ['series_10',['Choosing Fraction for Time Series',['../md_docs_2use-case-time-series.html#autotoc_md340',1,'']]],
  ['series_20analysis_11',['Time Series Analysis',['../md_docs_2use-case-time-series.html',1,'']]],
  ['signal_20smoothing_12',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md299',1,'']]],
  ['smoothing_13',['smoothing',['../md_docs_2quickstart.html#autotoc_md256',1,'Basic Smoothing'],['../md_docs_2use-case-genomics.html#autotoc_md299',1,'ChIP-seq Signal Smoothing'],['../md_docs_2use-case-genomics.html',1,'Genomic Data Smoothing'],['../md_docs_2use-case-genomics.html#autotoc_md295',1,'Methylation Profile Smoothing']]],
  ['solution_14',['Solution',['../md_docs_2use-case-genomics.html#autotoc_md297',1,'']]],
  ['source_15',['From Source',['../md_docs_2installation.html#autotoc_md141',1,'']]],
  ['spatial_20surface_16',['2D — Spatial Surface',['../md_docs_2dimensions.html#autotoc_md132',1,'']]],
  ['standard_20default_17',['1D — Standard (Default)',['../md_docs_2dimensions.html#autotoc_md130',1,'']]],
  ['standard_20errors_18',['Standard Errors',['../md_docs_2intervals.html#autotoc_md156',1,'']]],
  ['start_19',['Quick Start',['../md_docs_2quickstart.html',1,'']]],
  ['steps_20',['steps',['../md_docs_2quickstart.html#autotoc_md264',1,'Next Steps'],['../index.html#autotoc_md78',1,'Next Steps']]],
  ['strategies_21',['Merge Strategies',['../md_docs_2merge.html',1,'']]],
  ['strategy_22',['Choosing a Strategy',['../md_docs_2merge.html#autotoc_md190',1,'']]],
  ['streaming_23',['Large Genome Coverage (Streaming)',['../md_docs_2use-case-genomics.html#autotoc_md302',1,'']]],
  ['streaming_20mode_24',['streaming mode',['../md_docs_2use-case-real-time.html#autotoc_md320',1,'Streaming Mode'],['../md_docs_2quickstart.html#autotoc_md262',1,'Streaming Mode']]],
  ['streaming_20mode_3a_20chunk_20processing_25',['Streaming Mode: Chunk Processing',['../md_docs_2use-case-real-time.html#autotoc_md313',1,'']]],
  ['streamingloess_20api_26',['StreamingLoess API',['../md_docs_2api-streaming.html',1,'']]],
  ['streamingoptions_20tt_20inherits_20tt_20loessoptions_20tt_27',['&lt;tt&gt;StreamingOptions&lt;/tt&gt; (inherits &lt;tt&gt;LoessOptions&lt;/tt&gt;)',['../md_docs_2api-streaming.html#autotoc_md20',1,'']]],
  ['structure_28',['structure',['../md_docs_2api-streaming.html#autotoc_md19',1,'Options Structure'],['../md_docs_2api-online.html#autotoc_md7',1,'Options Structure'],['../md_docs_2api.html#autotoc_md30',1,'Result Structure'],['../md_docs_2api-streaming.html#autotoc_md17',1,'Result Structure'],['../md_docs_2api-online.html#autotoc_md9',1,'Result Structure']]],
  ['structures_29',['Options Structures',['../md_docs_2api.html#autotoc_md28',1,'']]],
  ['summary_30',['Parameter Options Summary',['../md_docs_2parameters.html#autotoc_md194',1,'']]],
  ['suppress_20a_20known_20outlier_31',['Suppress a Known Outlier',['../md_docs_2custom-weights.html#autotoc_md104',1,'']]],
  ['surface_32',['2D — Spatial Surface',['../md_docs_2dimensions.html#autotoc_md132',1,'']]],
  ['surface_20mode_33',['Surface Mode',['../md_docs_2degree.html#autotoc_md126',1,'']]],
  ['surface_5fmode_34',['surface_mode',['../md_docs_2api.html#autotoc_md41',1,'surface_mode'],['../md_docs_2parameters.html#autotoc_md203',1,'surface_mode']]]
];
