var searchData=
[
  ['cell_0',['cell',['../md_docs_2parameters.html#autotoc_md223',1,'']]],
  ['challenge_1',['The Challenge',['../md_docs_2use-case-genomics.html#autotoc_md314',1,'']]],
  ['changelog_2',['Changelog',['../index.html#autotoc_md15',1,'']]],
  ['chip_20seq_20signal_20smoothing_3',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md317',1,'']]],
  ['choosing_20a_20kernel_4',['Choosing a Kernel',['../md_docs_2kernels.html#autotoc_md196',1,'']]],
  ['choosing_20a_20policy_5',['Choosing a Policy',['../md_docs_2boundary.html#autotoc_md78',1,'']]],
  ['choosing_20a_20scaling_20method_6',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md309',1,'']]],
  ['choosing_20a_20strategy_7',['Choosing a Strategy',['../md_docs_2merge.html#autotoc_md208',1,'']]],
  ['choosing_20fraction_20for_20time_20series_8',['Choosing Fraction for Time Series',['../md_docs_2use-case-time-series.html#autotoc_md358',1,'']]],
  ['choosing_20parameters_9',['Choosing Parameters',['../md_docs_2use-case-real-time.html#autotoc_md336',1,'']]],
  ['choosing_20the_20right_20degree_10',['Choosing the Right Degree',['../md_docs_2degree.html#autotoc_md140',1,'']]],
  ['chunk_20processing_11',['Streaming Mode: Chunk Processing',['../md_docs_2use-case-real-time.html#autotoc_md331',1,'']]],
  ['chunk_5fsize_12',['chunk_size',['../md_docs_2parameters.html#autotoc_md262',1,'']]],
  ['citation_13',['Citation',['../index.html#autotoc_md17',1,'']]],
  ['class_14',['class',['../md_docs_2api-streaming.html#autotoc_md33',1,'Class'],['../md_docs_2api-online.html#autotoc_md23',1,'Class']]],
  ['classes_15',['Classes',['../md_docs_2api.html#autotoc_md44',1,'']]],
  ['comparison_16',['comparison',['../md_docs_2robustness.html#autotoc_md293',1,'Comparison'],['../md_docs_2cross-validation.html#autotoc_md106',1,'Comparison']]],
  ['concepts_17',['Concepts',['../md_docs_2concepts.html',1,'']]],
  ['concepts_2emd_18',['concepts.md',['../concepts_8md.html',1,'']]],
  ['conda_20forge_19',['From conda-forge',['../md_docs_2installation.html#autotoc_md160',1,'']]],
  ['confidence_20intervals_20',['confidence intervals',['../md_docs_2intervals.html#autotoc_md166',1,'Confidence Intervals'],['../md_docs_2quickstart.html#autotoc_md276',1,'With Confidence Intervals']]],
  ['confidence_20levels_21',['Confidence Levels',['../md_docs_2intervals.html#autotoc_md172',1,'']]],
  ['confidence_20vs_20prediction_20intervals_22',['Confidence vs Prediction Intervals',['../md_docs_2concepts.html#autotoc_md88',1,'']]],
  ['confidence_5fintervals_20prediction_5fintervals_23',['confidence_intervals / prediction_intervals',['../md_docs_2parameters.html#autotoc_md256',1,'']]],
  ['considerations_24',['Performance Considerations',['../md_docs_2use-case-real-time.html#autotoc_md340',1,'']]],
  ['constant_25',['Degree 0 — Local Constant',['../md_docs_2degree.html#autotoc_md130',1,'']]],
  ['contributing_26',['Contributing',['../index.html#autotoc_md14',1,'']]],
  ['convergence_27',['Auto-Convergence',['../md_docs_2robustness.html#autotoc_md299',1,'']]],
  ['core_20parameters_28',['Core Parameters',['../md_docs_2parameters.html#autotoc_md214',1,'']]],
  ['cosine_29',['Cosine',['../md_docs_2kernels.html#autotoc_md190',1,'']]],
  ['course_30',['Gene Expression Time Course',['../md_docs_2use-case-time-series.html#autotoc_md356',1,'']]],
  ['coverage_20streaming_31',['Large Genome Coverage (Streaming)',['../md_docs_2use-case-genomics.html#autotoc_md320',1,'']]],
  ['cpp_20view_20the_20full_20documentation_20a_32',['📚 &lt;a href=&quot;https://thisisamirv.github.io/loess-project/cpp/&quot; &gt;View the full documentation&lt;/a&gt;',['../index.html#autotoc_md3',1,'']]],
  ['cpu_20benchmarks_33',['CPU Benchmarks',['../md_docs_2benchmarks.html#autotoc_md64',1,'']]],
  ['cross_20validation_34',['cross validation',['../md_docs_2cross-validation.html',1,'Cross-Validation'],['../md_docs_2cross-validation.html#autotoc_md100',1,'K-Fold Cross-Validation']]],
  ['cross_2dvalidation_2emd_35',['cross-validation.md',['../cross-validation_8md.html',1,'']]],
  ['cubic_36',['Degree 3 — Local Cubic',['../md_docs_2degree.html#autotoc_md136',1,'']]],
  ['custom_20weights_37',['custom weights',['../md_docs_2custom-weights.html',1,'Custom Weights'],['../md_docs_2custom-weights.html#autotoc_md118',1,'When to Use Custom Weights']]],
  ['custom_20weights_20vs_20robustness_20iterations_38',['Custom Weights vs. Robustness Iterations',['../md_docs_2custom-weights.html#autotoc_md119',1,'']]],
  ['custom_20weights_20work_39',['How Custom Weights Work',['../md_docs_2custom-weights.html#autotoc_md116',1,'']]],
  ['custom_2dweights_2emd_40',['custom-weights.md',['../custom-weights_8md.html',1,'']]],
  ['custom_5fweights_41',['custom_weights',['../md_docs_2parameters.html#autotoc_md247',1,'']]],
  ['cv_20methods_42',['CV Methods',['../md_docs_2parameters.html#autotoc_md258',1,'']]],
  ['cv_20metrics_43',['CV Metrics',['../md_docs_2cross-validation.html#autotoc_md108',1,'']]],
  ['cv_5fmethod_44',['cv_method',['../md_docs_2parameters.html#autotoc_md259',1,'']]]
];
