var searchData=
[
  ['basic_20smoothing_0',['Basic Smoothing',['../md_docs_2quickstart.html#autotoc_md274',1,'']]],
  ['basic_20trend_20extraction_1',['Basic Trend Extraction',['../md_docs_2use-case-time-series.html#autotoc_md346',1,'']]],
  ['basic_20usage_2',['Basic Usage',['../md_docs_2custom-weights.html#autotoc_md121',1,'']]],
  ['benchmarks_3',['benchmarks',['../md_docs_2benchmarks.html',1,'Benchmarks'],['../md_docs_2benchmarks.html#autotoc_md64',1,'CPU Benchmarks'],['../md_docs_2benchmarks.html#autotoc_md66',1,'Reproducing Benchmarks']]],
  ['benchmarks_2emd_4',['benchmarks.md',['../benchmarks_8md.html',1,'']]],
  ['best_20practices_5',['Best Practices',['../md_docs_2cross-validation.html#autotoc_md114',1,'']]],
  ['best_20practices_20for_20genomic_20data_6',['Best Practices for Genomic Data',['../md_docs_2use-case-genomics.html#autotoc_md322',1,'']]],
  ['binaries_20linux_20x64_7',['Pre-built Binaries (Linux (x64))',['../md_docs_2installation.html#autotoc_md156',1,'']]],
  ['binaries_20macos_20x64_8',['Pre-built Binaries (macOS (x64))',['../md_docs_2installation.html#autotoc_md157',1,'']]],
  ['binaries_20windows_20x64_9',['Pre-built Binaries (Windows (x64))',['../md_docs_2installation.html#autotoc_md158',1,'']]],
  ['bisquare_20default_10',['Bisquare (Default)',['../md_docs_2robustness.html#autotoc_md287',1,'']]],
  ['biweight_11',['Biweight',['../md_docs_2kernels.html#autotoc_md188',1,'']]],
  ['blockquote_12',['blockquote',['../index.html#autotoc_md6',1,'&lt;/blockquote&gt;'],['../index.html#autotoc_md4',1,'&lt;/blockquote&gt;']]],
  ['both_20intervals_13',['Both Intervals',['../md_docs_2intervals.html#autotoc_md170',1,'']]],
  ['boundary_14',['No Boundary',['../md_docs_2boundary.html#autotoc_md76',1,'']]],
  ['boundary_20handling_15',['Boundary Handling',['../md_docs_2boundary.html',1,'']]],
  ['boundary_2emd_16',['boundary.md',['../boundary_8md.html',1,'']]],
  ['boundary_5fdegree_5ffallback_17',['boundary_degree_fallback',['../md_docs_2parameters.html#autotoc_md237',1,'']]],
  ['boundary_5fpolicy_18',['boundary_policy',['../md_docs_2parameters.html#autotoc_md235',1,'boundary_policy'],['../md_docs_2api.html#autotoc_md54',1,'boundary_policy']]],
  ['built_20binaries_20linux_20x64_19',['Pre-built Binaries (Linux (x64))',['../md_docs_2installation.html#autotoc_md156',1,'']]],
  ['built_20binaries_20macos_20x64_20',['Pre-built Binaries (macOS (x64))',['../md_docs_2installation.html#autotoc_md157',1,'']]],
  ['built_20binaries_20windows_20x64_21',['Pre-built Binaries (Windows (x64))',['../md_docs_2installation.html#autotoc_md158',1,'']]],
  ['by_20point_22',['Online Mode: Point-by-Point',['../md_docs_2use-case-real-time.html#autotoc_md328',1,'']]]
];
