var searchData=
[
  ['c_20api_20reference_0',['c api reference',['../md_docs_2api.html',1,'fastLoess C++ API Reference'],['../md_docs_2api-online.html',1,'OnlineLoess — C++ API Reference'],['../md_docs_2api-streaming.html',1,'StreamingLoess — C++ API Reference']]],
  ['case_20genomics_1',['use-case-genomics',['../md_docs_2use-case-genomics.html',1,'']]],
  ['case_20real_20time_2',['use-case-real-time',['../md_docs_2use-case-real-time.html',1,'']]],
  ['case_20time_20series_3',['use-case-time-series',['../md_docs_2use-case-time-series.html',1,'']]],
  ['cell_4',['cell',['../md_docs_2parameters.html#autotoc_md197',1,'']]],
  ['challenge_5',['The Challenge',['../md_docs_2use-case-genomics.html#autotoc_md294',1,'']]],
  ['chip_20seq_20signal_20smoothing_6',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md297',1,'']]],
  ['choice_7',['adapter-choice',['../md_docs_2adapter-choice.html',1,'']]],
  ['choosing_20a_20kernel_8',['Choosing a Kernel',['../md_docs_2kernels.html#autotoc_md164',1,'']]],
  ['choosing_20a_20policy_9',['Choosing a Policy',['../md_docs_2boundary.html#autotoc_md60',1,'']]],
  ['choosing_20a_20scaling_20method_10',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md283',1,'']]],
  ['choosing_20a_20strategy_11',['Choosing a Strategy',['../md_docs_2merge.html#autotoc_md176',1,'']]],
  ['choosing_20fraction_20for_20time_20series_12',['Choosing Fraction for Time Series',['../md_docs_2use-case-time-series.html#autotoc_md338',1,'']]],
  ['choosing_20parameters_13',['Choosing Parameters',['../md_docs_2use-case-real-time.html#autotoc_md316',1,'']]],
  ['choosing_20the_20right_20degree_14',['Choosing the Right Degree',['../md_docs_2degree.html#autotoc_md108',1,'']]],
  ['chunk_20processing_15',['Streaming Mode: Chunk Processing',['../md_docs_2use-case-real-time.html#autotoc_md311',1,'']]],
  ['chunk_5fsize_16',['chunk_size',['../md_docs_2parameters.html#autotoc_md236',1,'']]],
  ['class_17',['class',['../md_docs_2api-streaming.html#autotoc_md13',1,'Class'],['../md_docs_2api-online.html#autotoc_md4',1,'Class']]],
  ['classes_18',['Classes',['../md_docs_2api.html#autotoc_md22',1,'']]],
  ['comparison_19',['comparison',['../md_docs_2cross-validation.html#autotoc_md86',1,'Comparison'],['../md_docs_2robustness.html#autotoc_md267',1,'Comparison']]],
  ['concepts_20',['Concepts',['../index.html#autotoc_md61',1,'']]],
  ['concepts_2emd_21',['concepts.md',['../concepts_8md.html',1,'']]],
  ['conda_20forge_22',['From conda-forge',['../md_docs_2installation.html#autotoc_md128',1,'']]],
  ['confidence_20intervals_23',['confidence intervals',['../md_docs_2intervals.html#autotoc_md134',1,'Confidence Intervals'],['../md_docs_2quickstart.html#autotoc_md250',1,'With Confidence Intervals']]],
  ['confidence_20levels_24',['Confidence Levels',['../md_docs_2intervals.html#autotoc_md140',1,'']]],
  ['confidence_20vs_20prediction_20intervals_25',['Confidence vs Prediction Intervals',['../index.html#autotoc_md70',1,'']]],
  ['confidence_5fintervals_20prediction_5fintervals_26',['confidence_intervals / prediction_intervals',['../md_docs_2parameters.html#autotoc_md230',1,'']]],
  ['considerations_27',['Performance Considerations',['../md_docs_2use-case-real-time.html#autotoc_md320',1,'']]],
  ['constant_28',['Degree 0 — Local Constant',['../md_docs_2degree.html#autotoc_md98',1,'']]],
  ['convergence_29',['Auto-Convergence',['../md_docs_2robustness.html#autotoc_md273',1,'']]],
  ['core_20parameters_30',['Core Parameters',['../md_docs_2parameters.html#autotoc_md188',1,'']]],
  ['cosine_31',['Cosine',['../md_docs_2kernels.html#autotoc_md158',1,'']]],
  ['course_32',['Gene Expression Time Course',['../md_docs_2use-case-time-series.html#autotoc_md336',1,'']]],
  ['coverage_20streaming_33',['Large Genome Coverage (Streaming)',['../md_docs_2use-case-genomics.html#autotoc_md300',1,'']]],
  ['cpu_20benchmarks_34',['CPU Benchmarks',['../md_docs_2benchmarks.html#autotoc_md46',1,'']]],
  ['cross_20validation_35',['cross validation',['../md_docs_2cross-validation.html#autotoc_md77',1,'Cross-Validation'],['../md_docs_2cross-validation.html',1,'cross-validation'],['../md_docs_2cross-validation.html#autotoc_md80',1,'K-Fold Cross-Validation']]],
  ['cross_2dvalidation_2emd_36',['cross-validation.md',['../cross-validation_8md.html',1,'']]],
  ['cubic_37',['Degree 3 — Local Cubic',['../md_docs_2degree.html#autotoc_md104',1,'']]],
  ['custom_5fweights_38',['custom_weights',['../md_docs_2parameters.html#autotoc_md221',1,'']]],
  ['cv_20methods_39',['CV Methods',['../md_docs_2parameters.html#autotoc_md232',1,'']]],
  ['cv_20metrics_40',['CV Metrics',['../md_docs_2cross-validation.html#autotoc_md88',1,'']]],
  ['cv_5fmethod_41',['cv_method',['../md_docs_2parameters.html#autotoc_md233',1,'']]]
];
