var searchData=
[
  ['scale_20analysis_0',['Multi-Scale Analysis',['../md_docs_2use-case-time-series.html#autotoc_md290',1,'']]],
  ['scale_20estimation_1',['Scale Estimation',['../md_docs_2robustness.html#autotoc_md233',1,'']]],
  ['scaling_20method_2',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md245',1,'']]],
  ['scaling_20methods_3',['Scaling Methods',['../md_docs_2scaling.html',1,'']]],
  ['scaling_2emd_4',['scaling.md',['../scaling_8md.html',1,'']]],
  ['scaling_5fmethod_5',['scaling_method',['../md_docs_2api.html#autotoc_md50',1,'']]],
  ['see_20also_6',['see also',['../md_docs_2use-case-time-series.html#autotoc_md296',1,'See Also'],['../md_docs_2custom-weights.html#autotoc_md115',1,'See Also'],['../md_docs_2use-case-genomics.html#autotoc_md260',1,'See Also'],['../md_docs_2use-case-real-time.html#autotoc_md278',1,'See Also']]],
  ['seeded_20randomization_7',['Seeded Randomization',['../md_docs_2cross-validation.html#autotoc_md96',1,'']]],
  ['sensor_20data_20example_8',['Sensor Data Example',['../md_docs_2use-case-real-time.html#autotoc_md265',1,'']]],
  ['seq_20signal_20smoothing_9',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md253',1,'']]],
  ['series_10',['Choosing Fraction for Time Series',['../md_docs_2use-case-time-series.html#autotoc_md294',1,'']]],
  ['series_20analysis_11',['Time Series Analysis',['../md_docs_2use-case-time-series.html',1,'']]],
  ['signal_20smoothing_12',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md253',1,'']]],
  ['smoothing_13',['smoothing',['../md_docs_2quickstart.html#autotoc_md210',1,'Basic Smoothing'],['../md_docs_2use-case-genomics.html#autotoc_md253',1,'ChIP-seq Signal Smoothing'],['../md_docs_2use-case-genomics.html',1,'Genomic Data Smoothing'],['../md_docs_2use-case-genomics.html#autotoc_md249',1,'Methylation Profile Smoothing']]],
  ['solution_14',['Solution',['../md_docs_2use-case-genomics.html#autotoc_md251',1,'']]],
  ['source_15',['From Source',['../md_docs_2installation.html#autotoc_md147',1,'']]],
  ['spatial_20surface_16',['2D — Spatial Surface',['../md_docs_2dimensions.html#autotoc_md138',1,'']]],
  ['speed_17',['Speed',['../index.html#autotoc_md5',1,'']]],
  ['standard_20default_18',['1D — Standard (Default)',['../md_docs_2dimensions.html#autotoc_md136',1,'']]],
  ['standard_20errors_19',['Standard Errors',['../md_docs_2intervals.html#autotoc_md162',1,'']]],
  ['start_20',['Quick Start',['../md_docs_2quickstart.html',1,'']]],
  ['steps_21',['steps',['../md_docs_2quickstart.html#autotoc_md218',1,'Next Steps'],['../md_docs_2concepts.html#autotoc_md88',1,'Next Steps']]],
  ['strategies_22',['Merge Strategies',['../md_docs_2merge.html',1,'']]],
  ['strategy_23',['Choosing a Strategy',['../md_docs_2merge.html#autotoc_md196',1,'']]],
  ['streaming_24',['Large Genome Coverage (Streaming)',['../md_docs_2use-case-genomics.html#autotoc_md256',1,'']]],
  ['streaming_20mode_25',['streaming mode',['../md_docs_2quickstart.html#autotoc_md216',1,'Streaming Mode'],['../md_docs_2use-case-real-time.html#autotoc_md274',1,'Streaming Mode']]],
  ['streaming_20mode_3a_20chunk_20processing_26',['Streaming Mode: Chunk Processing',['../md_docs_2use-case-real-time.html#autotoc_md267',1,'']]],
  ['streamingloess_20api_27',['StreamingLoess API',['../md_docs_2api-streaming.html',1,'']]],
  ['streamingoptions_20inherits_20loessoptions_28',['StreamingOptions (inherits LoessOptions)',['../md_docs_2api-streaming.html#autotoc_md33',1,'']]],
  ['structure_29',['structure',['../md_docs_2api-streaming.html#autotoc_md32',1,'Options Structure'],['../md_docs_2api-online.html#autotoc_md20',1,'Options Structure'],['../md_docs_2api-streaming.html#autotoc_md30',1,'Result Structure'],['../md_docs_2api-online.html#autotoc_md22',1,'Result Structure'],['../md_docs_2api.html#autotoc_md43',1,'Result Structure']]],
  ['structures_30',['Options Structures',['../md_docs_2api.html#autotoc_md41',1,'']]],
  ['suppress_20a_20known_20outlier_31',['Suppress a Known Outlier',['../md_docs_2custom-weights.html#autotoc_md112',1,'']]],
  ['surface_32',['2D — Spatial Surface',['../md_docs_2dimensions.html#autotoc_md138',1,'']]],
  ['surface_20mode_33',['Surface Mode',['../md_docs_2degree.html#autotoc_md133',1,'']]],
  ['surface_5fmode_34',['surface_mode',['../md_docs_2api.html#autotoc_md54',1,'']]]
];
