var searchData=
[
  ['fastloess_0',['fastLoess',['../index.html',1,'']]],
  ['fastloess_20c_200_209_200_1',['fastloess (C++) 0.9.0',['../md_docs_2NEWS.html#autotoc_md206',1,'']]],
  ['fastloess_20c_201_200_200_2',['fastloess (C++) 1.0.0',['../md_docs_2NEWS.html#autotoc_md204',1,'']]],
  ['fastloess_20c_201_201_200_3',['fastloess (C++) 1.1.0',['../md_docs_2NEWS.html#autotoc_md200',1,'']]],
  ['fastloess_20c_20development_20version_4',['fastloess (C++) (development version)',['../md_docs_2NEWS.html#autotoc_md197',1,'']]],
  ['fastloess_3a_3adiagnostics_5',['fastloess::Diagnostics',['../md_docs_2api.html#autotoc_md45',1,'']]],
  ['fastloess_3a_3aloess_6',['fastloess::Loess',['../md_docs_2api.html#autotoc_md40',1,'']]],
  ['fastloess_3a_3aloessresult_7',['fastloess::loessresult',['../md_docs_2api-streaming.html#autotoc_md31',1,'fastloess::LoessResult'],['../md_docs_2api.html#autotoc_md44',1,'fastloess::LoessResult']]],
  ['fastloess_3a_3aonlineloess_8',['fastloess::OnlineLoess',['../md_docs_2api-online.html#autotoc_md19',1,'']]],
  ['fastloess_3a_3aonlineoutput_9',['fastloess::OnlineOutput',['../md_docs_2api-online.html#autotoc_md23',1,'']]],
  ['fastloess_3a_3astreamingloess_10',['fastloess::StreamingLoess',['../md_docs_2api-streaming.html#autotoc_md29',1,'']]],
  ['features_11',['Features',['../index.html#autotoc_md7',1,'']]],
  ['file_20processing_12',['Log File Processing',['../md_docs_2use-case-real-time.html#autotoc_md268',1,'']]],
  ['first_13',['Take First',['../md_docs_2merge.html#autotoc_md190',1,'']]],
  ['fixed_14',['fixed',['../md_docs_2NEWS.html#autotoc_md199',1,'Fixed'],['../md_docs_2NEWS.html#autotoc_md203',1,'Fixed']]],
  ['fold_20cross_20validation_15',['K-Fold Cross-Validation',['../md_docs_2cross-validation.html#autotoc_md92',1,'']]],
  ['for_20genomic_20data_16',['Best Practices for Genomic Data',['../md_docs_2use-case-genomics.html#autotoc_md258',1,'']]],
  ['for_20multivariate_20data_17',['Distance Metrics for Multivariate Data',['../md_docs_2dimensions.html#autotoc_md142',1,'']]],
  ['for_20time_20series_18',['Choosing Fraction for Time Series',['../md_docs_2use-case-time-series.html#autotoc_md294',1,'']]],
  ['forecasting_20with_20prediction_20intervals_19',['Forecasting with Prediction Intervals',['../md_docs_2use-case-time-series.html#autotoc_md286',1,'']]],
  ['forge_20',['From conda-forge',['../md_docs_2installation.html#autotoc_md148',1,'']]],
  ['fraction_20for_20time_20series_21',['Choosing Fraction for Time Series',['../md_docs_2use-case-time-series.html#autotoc_md294',1,'']]],
  ['fraction_20parameter_22',['The Fraction Parameter',['../md_docs_2concepts.html#autotoc_md77',1,'']]],
  ['from_20conda_20forge_23',['From conda-forge',['../md_docs_2installation.html#autotoc_md148',1,'']]],
  ['from_20source_24',['From Source',['../md_docs_2installation.html#autotoc_md147',1,'']]],
  ['functions_25',['Weight Functions',['../md_docs_2kernels.html',1,'']]]
];
