var searchData=
[
  ['basic_20smoothing_0',['Basic Smoothing',['../md_docs_2quickstart.html#autotoc_md254',1,'']]],
  ['basic_20trend_20extraction_1',['Basic Trend Extraction',['../md_docs_2use-case-time-series.html#autotoc_md326',1,'']]],
  ['basic_20usage_2',['Basic Usage',['../md_docs_2custom-weights.html#autotoc_md101',1,'']]],
  ['benchmarks_3',['benchmarks',['../md_docs_2benchmarks.html',1,'Benchmarks'],['../md_docs_2benchmarks.html#autotoc_md46',1,'CPU Benchmarks'],['../md_docs_2benchmarks.html#autotoc_md48',1,'Reproducing Benchmarks']]],
  ['benchmarks_2emd_4',['benchmarks.md',['../benchmarks_8md.html',1,'']]],
  ['best_20practices_5',['Best Practices',['../md_docs_2cross-validation.html#autotoc_md94',1,'']]],
  ['best_20practices_20for_20genomic_20data_6',['Best Practices for Genomic Data',['../md_docs_2use-case-genomics.html#autotoc_md302',1,'']]],
  ['binaries_20linux_20x64_7',['Pre-built Binaries (Linux (x64))',['../md_docs_2installation.html#autotoc_md136',1,'']]],
  ['binaries_20macos_20x64_8',['Pre-built Binaries (macOS (x64))',['../md_docs_2installation.html#autotoc_md137',1,'']]],
  ['binaries_20windows_20x64_9',['Pre-built Binaries (Windows (x64))',['../md_docs_2installation.html#autotoc_md138',1,'']]],
  ['bisquare_20default_10',['Bisquare (Default)',['../md_docs_2robustness.html#autotoc_md267',1,'']]],
  ['biweight_11',['Biweight',['../md_docs_2kernels.html#autotoc_md168',1,'']]],
  ['both_20intervals_12',['Both Intervals',['../md_docs_2intervals.html#autotoc_md150',1,'']]],
  ['boundary_13',['No Boundary',['../md_docs_2boundary.html#autotoc_md58',1,'']]],
  ['boundary_20handling_14',['Boundary Handling',['../md_docs_2boundary.html',1,'']]],
  ['boundary_2emd_15',['boundary.md',['../boundary_8md.html',1,'']]],
  ['boundary_5fdegree_5ffallback_16',['boundary_degree_fallback',['../md_docs_2parameters.html#autotoc_md217',1,'']]],
  ['boundary_5fpolicy_17',['boundary_policy',['../md_docs_2parameters.html#autotoc_md215',1,'boundary_policy'],['../md_docs_2api.html#autotoc_md36',1,'boundary_policy']]],
  ['built_20binaries_20linux_20x64_18',['Pre-built Binaries (Linux (x64))',['../md_docs_2installation.html#autotoc_md136',1,'']]],
  ['built_20binaries_20macos_20x64_19',['Pre-built Binaries (macOS (x64))',['../md_docs_2installation.html#autotoc_md137',1,'']]],
  ['built_20binaries_20windows_20x64_20',['Pre-built Binaries (Windows (x64))',['../md_docs_2installation.html#autotoc_md138',1,'']]],
  ['by_20point_21',['Online Mode: Point-by-Point',['../md_docs_2use-case-real-time.html#autotoc_md308',1,'']]]
];
