var searchData=
[
  ['c_200_209_200_0',['fastloess (C++) 0.9.0',['../md_docs_2NEWS.html#autotoc_md206',1,'']]],
  ['c_201_200_200_1',['fastloess (C++) 1.0.0',['../md_docs_2NEWS.html#autotoc_md204',1,'']]],
  ['c_201_201_200_2',['fastloess (C++) 1.1.0',['../md_docs_2NEWS.html#autotoc_md200',1,'']]],
  ['c_20development_20version_3',['fastloess (C++) (development version)',['../md_docs_2NEWS.html#autotoc_md197',1,'']]],
  ['challenge_4',['The Challenge',['../md_docs_2use-case-genomics.html#autotoc_md250',1,'']]],
  ['changed_5',['changed',['../md_docs_2NEWS.html#autotoc_md198',1,'Changed'],['../md_docs_2NEWS.html#autotoc_md202',1,'Changed'],['../md_docs_2NEWS.html#autotoc_md205',1,'Changed'],['../md_docs_2NEWS.html#autotoc_md208',1,'Changed']]],
  ['chip_20seq_20signal_20smoothing_6',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md253',1,'']]],
  ['choosing_20a_20kernel_7',['Choosing a Kernel',['../md_docs_2kernels.html#autotoc_md184',1,'']]],
  ['choosing_20a_20policy_8',['Choosing a Policy',['../md_docs_2boundary.html#autotoc_md71',1,'']]],
  ['choosing_20a_20scaling_20method_9',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md245',1,'']]],
  ['choosing_20a_20strategy_10',['Choosing a Strategy',['../md_docs_2merge.html#autotoc_md196',1,'']]],
  ['choosing_20fraction_20for_20time_20series_11',['Choosing Fraction for Time Series',['../md_docs_2use-case-time-series.html#autotoc_md294',1,'']]],
  ['choosing_20parameters_12',['Choosing Parameters',['../md_docs_2use-case-real-time.html#autotoc_md272',1,'']]],
  ['choosing_20the_20right_20degree_13',['Choosing the Right Degree',['../md_docs_2degree.html#autotoc_md129',1,'']]],
  ['chunk_20processing_14',['Streaming Mode: Chunk Processing',['../md_docs_2use-case-real-time.html#autotoc_md267',1,'']]],
  ['citation_15',['Citation',['../index.html#autotoc_md12',1,'']]],
  ['class_16',['class',['../md_docs_2api-online.html#autotoc_md18',1,'Class'],['../md_docs_2api-streaming.html#autotoc_md28',1,'Class']]],
  ['classes_17',['Classes',['../md_docs_2api.html#autotoc_md39',1,'']]],
  ['comparison_18',['comparison',['../md_docs_2cross-validation.html#autotoc_md98',1,'Comparison'],['../md_docs_2robustness.html#autotoc_md229',1,'Comparison']]],
  ['concepts_19',['Concepts',['../md_docs_2concepts.html',1,'']]],
  ['concepts_2emd_20',['concepts.md',['../concepts_8md.html',1,'']]],
  ['conda_20forge_21',['From conda-forge',['../md_docs_2installation.html#autotoc_md148',1,'']]],
  ['confidence_20intervals_22',['confidence intervals',['../md_docs_2intervals.html#autotoc_md154',1,'Confidence Intervals'],['../md_docs_2quickstart.html#autotoc_md212',1,'With Confidence Intervals']]],
  ['confidence_20levels_23',['Confidence Levels',['../md_docs_2intervals.html#autotoc_md160',1,'']]],
  ['confidence_20vs_20prediction_20intervals_24',['Confidence vs Prediction Intervals',['../md_docs_2concepts.html#autotoc_md80',1,'']]],
  ['considerations_25',['Performance Considerations',['../md_docs_2use-case-real-time.html#autotoc_md276',1,'']]],
  ['constant_26',['Degree 0 — Local Constant',['../md_docs_2degree.html#autotoc_md119',1,'']]],
  ['contributing_27',['Contributing',['../index.html#autotoc_md10',1,'']]],
  ['convergence_28',['Auto-Convergence',['../md_docs_2robustness.html#autotoc_md235',1,'']]],
  ['cosine_29',['Cosine',['../md_docs_2kernels.html#autotoc_md178',1,'']]],
  ['course_30',['Gene Expression Time Course',['../md_docs_2use-case-time-series.html#autotoc_md292',1,'']]],
  ['coverage_20streaming_31',['Large Genome Coverage (Streaming)',['../md_docs_2use-case-genomics.html#autotoc_md256',1,'']]],
  ['cpu_20benchmarks_32',['CPU Benchmarks',['../md_docs_2benchmarks.html#autotoc_md57',1,'']]],
  ['cross_20validation_33',['cross validation',['../md_docs_2cross-validation.html',1,'Cross-Validation'],['../md_docs_2cross-validation.html#autotoc_md92',1,'K-Fold Cross-Validation']]],
  ['cross_2dvalidation_2emd_34',['cross-validation.md',['../cross-validation_8md.html',1,'']]],
  ['cubic_35',['Degree 3 — Local Cubic',['../md_docs_2degree.html#autotoc_md125',1,'']]],
  ['custom_20weights_36',['custom weights',['../md_docs_2custom-weights.html',1,'Custom Weights'],['../md_docs_2custom-weights.html#autotoc_md108',1,'When to Use Custom Weights']]],
  ['custom_20weights_20vs_20robustness_20iterations_37',['Custom Weights vs. Robustness Iterations',['../md_docs_2custom-weights.html#autotoc_md109',1,'']]],
  ['custom_20weights_20work_38',['How Custom Weights Work',['../md_docs_2custom-weights.html#autotoc_md107',1,'']]],
  ['custom_2dweights_2emd_39',['custom-weights.md',['../custom-weights_8md.html',1,'']]],
  ['cv_20metrics_40',['CV Metrics',['../md_docs_2cross-validation.html#autotoc_md99',1,'']]]
];
