var searchData=
[
  ['macos_20x64_0',['Pre-built Binaries (macOS (x64))',['../md_docs_2installation.html#autotoc_md125',1,'']]],
  ['mad_20—_20median_20absolute_20deviation_20default_1',['MAD — Median Absolute Deviation (Default)',['../md_docs_2scaling.html#autotoc_md277',1,'']]],
  ['mar_20—_20median_20absolute_20residual_2',['MAR — Median Absolute Residual',['../md_docs_2scaling.html#autotoc_md279',1,'']]],
  ['mean_20—_20mean_20absolute_20residual_3',['Mean — Mean Absolute Residual',['../md_docs_2scaling.html#autotoc_md281',1,'']]],
  ['median_20absolute_20deviation_20default_4',['MAD — Median Absolute Deviation (Default)',['../md_docs_2scaling.html#autotoc_md277',1,'']]],
  ['median_20absolute_20residual_5',['MAR — Median Absolute Residual',['../md_docs_2scaling.html#autotoc_md279',1,'']]],
  ['merge_6',['merge',['../md_docs_2merge.html',1,'']]],
  ['merge_20strategies_7',['merge strategies',['../md_docs_2streaming.html#autotoc_md287',1,'Merge Strategies'],['../md_docs_2merge.html#autotoc_md165',1,'Merge Strategies']]],
  ['merge_2emd_8',['merge.md',['../merge_8md.html',1,'']]],
  ['merge_5fstrategy_9',['merge_strategy',['../md_docs_2parameters.html#autotoc_md240',1,'merge_strategy'],['../md_docs_2api-streaming.html#autotoc_md20',1,'merge_strategy'],['../md_docs_2api.html#autotoc_md38',1,'merge_strategy']]],
  ['method_10',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md283',1,'']]],
  ['methods_11',['methods',['../md_docs_2parameters.html#autotoc_md232',1,'CV Methods'],['../md_docs_2robustness.html#autotoc_md260',1,'Robustness Methods'],['../md_docs_2scaling.html#autotoc_md274',1,'Scaling Methods']]],
  ['methylation_20profile_20smoothing_12',['Methylation Profile Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md293',1,'']]],
  ['metrics_13',['CV Metrics',['../md_docs_2cross-validation.html#autotoc_md88',1,'']]],
  ['metrics_20for_20multivariate_20data_14',['Distance Metrics for Multivariate Data',['../md_docs_2dimensions.html#autotoc_md122',1,'']]],
  ['min_5fpoints_15',['min_points',['../md_docs_2parameters.html#autotoc_md244',1,'']]],
  ['missing_20data_16',['Handling Missing Data',['../md_docs_2use-case-time-series.html#autotoc_md332',1,'']]],
  ['mode_17',['mode',['../md_docs_2use-case-real-time.html#autotoc_md317',1,'Online Mode'],['../md_docs_2use-case-real-time.html#autotoc_md318',1,'Streaming Mode'],['../md_docs_2quickstart.html#autotoc_md254',1,'Streaming Mode'],['../md_docs_2degree.html#autotoc_md112',1,'Surface Mode']]],
  ['mode_3a_20chunk_20processing_18',['Streaming Mode: Chunk Processing',['../md_docs_2use-case-real-time.html#autotoc_md311',1,'']]],
  ['mode_3a_20point_20by_20point_19',['Online Mode: Point-by-Point',['../md_docs_2use-case-real-time.html#autotoc_md308',1,'']]],
  ['modes_20',['modes',['../index.html#autotoc_md72',1,'Execution Modes'],['../md_docs_2adapter-choice.html#autotoc_md0',1,'Execution Modes'],['../md_docs_2online.html#autotoc_md180',1,'Update Modes']]],
  ['multi_20scale_20analysis_21',['Multi-Scale Analysis',['../md_docs_2use-case-time-series.html#autotoc_md334',1,'']]],
  ['multivariate_20data_22',['Distance Metrics for Multivariate Data',['../md_docs_2dimensions.html#autotoc_md122',1,'']]],
  ['multivariate_20loess_23',['Multivariate LOESS',['../md_docs_2dimensions.html#autotoc_md113',1,'']]]
];
