var searchData=
[
  ['scale_20analysis_0',['Multi-Scale Analysis',['../md_docs_2use-case-time-series.html#autotoc_md334',1,'']]],
  ['scale_20estimation_1',['Scale Estimation',['../md_docs_2robustness.html#autotoc_md271',1,'']]],
  ['scaling_2',['scaling',['../md_docs_2scaling.html',1,'']]],
  ['scaling_20method_3',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md283',1,'']]],
  ['scaling_20methods_4',['Scaling Methods',['../md_docs_2scaling.html#autotoc_md274',1,'']]],
  ['scaling_2emd_5',['scaling.md',['../scaling_8md.html',1,'']]],
  ['scaling_5fmethod_6',['scaling_method',['../md_docs_2parameters.html#autotoc_md213',1,'scaling_method'],['../md_docs_2api.html#autotoc_md33',1,'scaling_method']]],
  ['see_20also_7',['see also',['../md_docs_2use-case-real-time.html#autotoc_md322',1,'See Also'],['../md_docs_2use-case-genomics.html#autotoc_md304',1,'See Also'],['../md_docs_2use-case-time-series.html#autotoc_md340',1,'See Also']]],
  ['seeded_20randomization_8',['Seeded Randomization',['../md_docs_2cross-validation.html#autotoc_md84',1,'']]],
  ['sensor_20data_20example_9',['Sensor Data Example',['../md_docs_2use-case-real-time.html#autotoc_md309',1,'']]],
  ['seq_20signal_20smoothing_10',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md297',1,'']]],
  ['series_11',['series',['../md_docs_2use-case-time-series.html#autotoc_md338',1,'Choosing Fraction for Time Series'],['../md_docs_2use-case-time-series.html',1,'use-case-time-series']]],
  ['series_20analysis_12',['Time Series Analysis',['../md_docs_2use-case-time-series.html#autotoc_md323',1,'']]],
  ['signal_20smoothing_13',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md297',1,'']]],
  ['smoothing_14',['smoothing',['../md_docs_2quickstart.html#autotoc_md248',1,'Basic Smoothing'],['../md_docs_2use-case-genomics.html#autotoc_md297',1,'ChIP-seq Signal Smoothing'],['../md_docs_2use-case-genomics.html#autotoc_md290',1,'Genomic Data Smoothing'],['../md_docs_2use-case-genomics.html#autotoc_md293',1,'Methylation Profile Smoothing']]],
  ['solution_15',['Solution',['../md_docs_2use-case-genomics.html#autotoc_md295',1,'']]],
  ['source_16',['From Source',['../md_docs_2installation.html#autotoc_md127',1,'']]],
  ['spatial_20surface_17',['2D — Spatial Surface',['../md_docs_2dimensions.html#autotoc_md118',1,'']]],
  ['standard_20default_18',['1D — Standard (Default)',['../md_docs_2dimensions.html#autotoc_md116',1,'']]],
  ['standard_20errors_19',['Standard Errors',['../md_docs_2intervals.html#autotoc_md142',1,'']]],
  ['start_20',['Quick Start',['../md_docs_2quickstart.html#autotoc_md247',1,'']]],
  ['steps_21',['steps',['../md_docs_2quickstart.html#autotoc_md256',1,'Next Steps'],['../index.html#autotoc_md76',1,'Next Steps']]],
  ['strategies_22',['strategies',['../md_docs_2merge.html#autotoc_md165',1,'Merge Strategies'],['../md_docs_2streaming.html#autotoc_md287',1,'Merge Strategies']]],
  ['strategy_23',['Choosing a Strategy',['../md_docs_2merge.html#autotoc_md176',1,'']]],
  ['streaming_24',['Large Genome Coverage (Streaming)',['../md_docs_2use-case-genomics.html#autotoc_md300',1,'']]],
  ['streaming_20adapter_25',['Streaming Adapter',['../md_docs_2streaming.html',1,'']]],
  ['streaming_20mode_26',['streaming mode',['../md_docs_2quickstart.html#autotoc_md254',1,'Streaming Mode'],['../md_docs_2use-case-real-time.html#autotoc_md318',1,'Streaming Mode']]],
  ['streaming_20mode_3a_20chunk_20processing_27',['Streaming Mode: Chunk Processing',['../md_docs_2use-case-real-time.html#autotoc_md311',1,'']]],
  ['streaming_2emd_28',['streaming.md',['../streaming_8md.html',1,'']]],
  ['streamingloess_20—_20c_20api_20reference_29',['StreamingLoess — C++ API Reference',['../md_docs_2api-streaming.html',1,'']]],
  ['streamingoptions_20tt_20inherits_20tt_20loessoptions_20tt_30',['&lt;tt&gt;StreamingOptions&lt;/tt&gt; (inherits &lt;tt&gt;LoessOptions&lt;/tt&gt;)',['../md_docs_2api-streaming.html#autotoc_md18',1,'']]],
  ['structure_31',['structure',['../md_docs_2api-streaming.html#autotoc_md17',1,'Options Structure'],['../md_docs_2api-online.html#autotoc_md6',1,'Options Structure'],['../md_docs_2api.html#autotoc_md26',1,'Result Structure'],['../md_docs_2api-streaming.html#autotoc_md15',1,'Result Structure'],['../md_docs_2api-online.html#autotoc_md8',1,'Result Structure']]],
  ['structures_32',['Options Structures',['../md_docs_2api.html#autotoc_md24',1,'']]],
  ['summary_33',['Parameter Options Summary',['../md_docs_2parameters.html#autotoc_md186',1,'']]],
  ['surface_34',['2D — Spatial Surface',['../md_docs_2dimensions.html#autotoc_md118',1,'']]],
  ['surface_20mode_35',['Surface Mode',['../md_docs_2degree.html#autotoc_md112',1,'']]],
  ['surface_5fmode_36',['surface_mode',['../md_docs_2parameters.html#autotoc_md195',1,'surface_mode'],['../md_docs_2api.html#autotoc_md37',1,'surface_mode']]]
];
