var searchData=
[
  ['a_20kernel_0',['Choosing a Kernel',['../md_docs_2kernels.html#autotoc_md178',1,'']]],
  ['a_20known_20outlier_1',['Suppress a Known Outlier',['../md_docs_2custom-weights.html#autotoc_md104',1,'']]],
  ['a_20policy_2',['Choosing a Policy',['../md_docs_2boundary.html#autotoc_md60',1,'']]],
  ['a_20scaling_20method_3',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md291',1,'']]],
  ['a_20strategy_4',['Choosing a Strategy',['../md_docs_2merge.html#autotoc_md190',1,'']]],
  ['absolute_20deviation_20default_5',['MAD — Median Absolute Deviation (Default)',['../md_docs_2scaling.html#autotoc_md285',1,'']]],
  ['absolute_20residual_6',['absolute residual',['../md_docs_2scaling.html#autotoc_md287',1,'MAR — Median Absolute Residual'],['../md_docs_2scaling.html#autotoc_md289',1,'Mean — Mean Absolute Residual']]],
  ['adapter_20parameters_7',['Adapter Parameters',['../md_docs_2parameters.html#autotoc_md243',1,'']]],
  ['adapter_2dchoice_2emd_8',['adapter-choice.md',['../adapter-choice_8md.html',1,'']]],
  ['advantages_9',['Key Advantages',['../index.html#autotoc_md76',1,'']]],
  ['also_10',['also',['../md_docs_2use-case-time-series.html#autotoc_md342',1,'See Also'],['../md_docs_2use-case-real-time.html#autotoc_md324',1,'See Also'],['../md_docs_2use-case-genomics.html#autotoc_md306',1,'See Also'],['../md_docs_2custom-weights.html#autotoc_md108',1,'See Also']]],
  ['analysis_11',['analysis',['../md_docs_2use-case-time-series.html#autotoc_md336',1,'Multi-Scale Analysis'],['../md_docs_2use-case-time-series.html',1,'Time Series Analysis']]],
  ['and_20higher_12',['3D and Higher',['../md_docs_2dimensions.html#autotoc_md134',1,'']]],
  ['api_13',['api',['../md_docs_2api.html',1,'API'],['../md_docs_2api-online.html',1,'OnlineLoess API'],['../md_docs_2api-streaming.html',1,'StreamingLoess API']]],
  ['api_2donline_2emd_14',['api-online.md',['../api-online_8md.html',1,'']]],
  ['api_2dstreaming_2emd_15',['api-streaming.md',['../api-streaming_8md.html',1,'']]],
  ['api_2emd_16',['api.md',['../api_8md.html',1,'']]],
  ['application_17',['Application',['../md_docs_2use-case-genomics.html#autotoc_md300',1,'']]],
  ['auto_20convergence_18',['Auto-Convergence',['../md_docs_2robustness.html#autotoc_md281',1,'']]],
  ['auto_5fconverge_19',['auto_converge',['../md_docs_2parameters.html#autotoc_md225',1,'']]],
  ['availability_20',['availability',['../md_docs_2cross-validation.html#autotoc_md94',1,'Availability'],['../md_docs_2intervals.html#autotoc_md158',1,'Availability']]],
  ['available_20kernels_21',['Available Kernels',['../md_docs_2kernels.html#autotoc_md162',1,'']]],
  ['average_22',['average',['../md_docs_2merge.html#autotoc_md182',1,'Average'],['../md_docs_2merge.html#autotoc_md188',1,'Weighted Average']]]
];
