var searchData=
[
  ['cell_0',['cell',['../md_docs_2parameters.html#autotoc_md203',1,'']]],
  ['challenge_1',['The Challenge',['../md_docs_2use-case-genomics.html#autotoc_md294',1,'']]],
  ['chip_20seq_20signal_20smoothing_2',['ChIP-seq Signal Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md297',1,'']]],
  ['choosing_20a_20kernel_3',['Choosing a Kernel',['../md_docs_2kernels.html#autotoc_md176',1,'']]],
  ['choosing_20a_20policy_4',['Choosing a Policy',['../md_docs_2boundary.html#autotoc_md60',1,'']]],
  ['choosing_20a_20scaling_20method_5',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md289',1,'']]],
  ['choosing_20a_20strategy_6',['Choosing a Strategy',['../md_docs_2merge.html#autotoc_md188',1,'']]],
  ['choosing_20fraction_20for_20time_20series_7',['Choosing Fraction for Time Series',['../md_docs_2use-case-time-series.html#autotoc_md338',1,'']]],
  ['choosing_20parameters_8',['Choosing Parameters',['../md_docs_2use-case-real-time.html#autotoc_md316',1,'']]],
  ['choosing_20the_20right_20degree_9',['Choosing the Right Degree',['../md_docs_2degree.html#autotoc_md120',1,'']]],
  ['chunk_20processing_10',['Streaming Mode: Chunk Processing',['../md_docs_2use-case-real-time.html#autotoc_md311',1,'']]],
  ['chunk_5fsize_11',['chunk_size',['../md_docs_2parameters.html#autotoc_md242',1,'']]],
  ['class_12',['class',['../md_docs_2api-streaming.html#autotoc_md15',1,'Class'],['../md_docs_2api-online.html#autotoc_md5',1,'Class']]],
  ['classes_13',['Classes',['../md_docs_2api.html#autotoc_md26',1,'']]],
  ['comparison_14',['comparison',['../md_docs_2robustness.html#autotoc_md273',1,'Comparison'],['../md_docs_2cross-validation.html#autotoc_md86',1,'Comparison']]],
  ['concepts_15',['Concepts',['../index.html',1,'']]],
  ['concepts_2emd_16',['concepts.md',['../concepts_8md.html',1,'']]],
  ['conda_20forge_17',['From conda-forge',['../md_docs_2installation.html#autotoc_md140',1,'']]],
  ['confidence_20intervals_18',['confidence intervals',['../md_docs_2intervals.html#autotoc_md146',1,'Confidence Intervals'],['../md_docs_2quickstart.html#autotoc_md256',1,'With Confidence Intervals']]],
  ['confidence_20levels_19',['Confidence Levels',['../md_docs_2intervals.html#autotoc_md152',1,'']]],
  ['confidence_20vs_20prediction_20intervals_20',['Confidence vs Prediction Intervals',['../index.html#autotoc_md70',1,'']]],
  ['confidence_5fintervals_20prediction_5fintervals_21',['confidence_intervals / prediction_intervals',['../md_docs_2parameters.html#autotoc_md236',1,'']]],
  ['considerations_22',['Performance Considerations',['../md_docs_2use-case-real-time.html#autotoc_md320',1,'']]],
  ['constant_23',['Degree 0 — Local Constant',['../md_docs_2degree.html#autotoc_md110',1,'']]],
  ['convergence_24',['Auto-Convergence',['../md_docs_2robustness.html#autotoc_md279',1,'']]],
  ['core_20parameters_25',['Core Parameters',['../md_docs_2parameters.html#autotoc_md194',1,'']]],
  ['cosine_26',['Cosine',['../md_docs_2kernels.html#autotoc_md170',1,'']]],
  ['course_27',['Gene Expression Time Course',['../md_docs_2use-case-time-series.html#autotoc_md336',1,'']]],
  ['coverage_20streaming_28',['Large Genome Coverage (Streaming)',['../md_docs_2use-case-genomics.html#autotoc_md300',1,'']]],
  ['cpu_20benchmarks_29',['CPU Benchmarks',['../md_docs_2benchmarks.html#autotoc_md46',1,'']]],
  ['cross_20validation_30',['cross validation',['../md_docs_2cross-validation.html',1,'Cross-Validation'],['../md_docs_2cross-validation.html#autotoc_md80',1,'K-Fold Cross-Validation']]],
  ['cross_2dvalidation_2emd_31',['cross-validation.md',['../cross-validation_8md.html',1,'']]],
  ['cubic_32',['Degree 3 — Local Cubic',['../md_docs_2degree.html#autotoc_md116',1,'']]],
  ['custom_20weights_33',['custom weights',['../md_docs_2custom-weights.html',1,'Custom Weights'],['../md_docs_2custom-weights.html#autotoc_md98',1,'When to Use Custom Weights']]],
  ['custom_20weights_20vs_20robustness_20iterations_34',['Custom Weights vs. Robustness Iterations',['../md_docs_2custom-weights.html#autotoc_md99',1,'']]],
  ['custom_20weights_20work_35',['How Custom Weights Work',['../md_docs_2custom-weights.html#autotoc_md96',1,'']]],
  ['custom_2dweights_2emd_36',['custom-weights.md',['../custom-weights_8md.html',1,'']]],
  ['custom_5fweights_37',['custom_weights',['../md_docs_2parameters.html#autotoc_md227',1,'']]],
  ['cv_20methods_38',['CV Methods',['../md_docs_2parameters.html#autotoc_md238',1,'']]],
  ['cv_20metrics_39',['CV Metrics',['../md_docs_2cross-validation.html#autotoc_md88',1,'']]],
  ['cv_5fmethod_40',['cv_method',['../md_docs_2parameters.html#autotoc_md239',1,'']]]
];
