var searchData=
[
  ['macos_20x64_0',['Pre-built Binaries (macOS (x64))',['../md_docs_2installation.html#autotoc_md139',1,'']]],
  ['mad_20—_20median_20absolute_20deviation_20default_1',['MAD — Median Absolute Deviation (Default)',['../md_docs_2scaling.html#autotoc_md285',1,'']]],
  ['mar_20—_20median_20absolute_20residual_2',['MAR — Median Absolute Residual',['../md_docs_2scaling.html#autotoc_md287',1,'']]],
  ['mean_20—_20mean_20absolute_20residual_3',['Mean — Mean Absolute Residual',['../md_docs_2scaling.html#autotoc_md289',1,'']]],
  ['median_20absolute_20deviation_20default_4',['MAD — Median Absolute Deviation (Default)',['../md_docs_2scaling.html#autotoc_md285',1,'']]],
  ['median_20absolute_20residual_5',['MAR — Median Absolute Residual',['../md_docs_2scaling.html#autotoc_md287',1,'']]],
  ['merge_20strategies_6',['Merge Strategies',['../md_docs_2merge.html',1,'']]],
  ['merge_2emd_7',['merge.md',['../merge_8md.html',1,'']]],
  ['merge_5fstrategy_8',['merge_strategy',['../md_docs_2api-streaming.html#autotoc_md22',1,'merge_strategy'],['../md_docs_2api.html#autotoc_md42',1,'merge_strategy'],['../md_docs_2parameters.html#autotoc_md248',1,'merge_strategy']]],
  ['method_9',['Choosing a Scaling Method',['../md_docs_2scaling.html#autotoc_md291',1,'']]],
  ['methods_10',['methods',['../md_docs_2parameters.html#autotoc_md240',1,'CV Methods'],['../md_docs_2robustness.html#autotoc_md268',1,'Robustness Methods'],['../md_docs_2scaling.html',1,'Scaling Methods']]],
  ['methylation_20profile_20smoothing_11',['Methylation Profile Smoothing',['../md_docs_2use-case-genomics.html#autotoc_md295',1,'']]],
  ['metrics_12',['CV Metrics',['../md_docs_2cross-validation.html#autotoc_md90',1,'']]],
  ['metrics_20for_20multivariate_20data_13',['Distance Metrics for Multivariate Data',['../md_docs_2dimensions.html#autotoc_md136',1,'']]],
  ['min_5fpoints_14',['min_points',['../md_docs_2parameters.html#autotoc_md252',1,'']]],
  ['missing_20data_15',['Handling Missing Data',['../md_docs_2use-case-time-series.html#autotoc_md334',1,'']]],
  ['mode_16',['mode',['../md_docs_2use-case-real-time.html#autotoc_md319',1,'Online Mode'],['../md_docs_2quickstart.html#autotoc_md262',1,'Streaming Mode'],['../md_docs_2use-case-real-time.html#autotoc_md320',1,'Streaming Mode'],['../md_docs_2degree.html#autotoc_md126',1,'Surface Mode']]],
  ['mode_3a_20chunk_20processing_17',['Streaming Mode: Chunk Processing',['../md_docs_2use-case-real-time.html#autotoc_md313',1,'']]],
  ['mode_3a_20point_20by_20point_18',['Online Mode: Point-by-Point',['../md_docs_2use-case-real-time.html#autotoc_md310',1,'']]],
  ['modes_19',['modes',['../md_docs_2adapter-choice.html',1,'Execution Modes'],['../index.html#autotoc_md72',1,'Execution Modes']]],
  ['multi_20scale_20analysis_20',['Multi-Scale Analysis',['../md_docs_2use-case-time-series.html#autotoc_md336',1,'']]],
  ['multivariate_20data_21',['Distance Metrics for Multivariate Data',['../md_docs_2dimensions.html#autotoc_md136',1,'']]],
  ['multivariate_20loess_22',['Multivariate LOESS',['../md_docs_2dimensions.html',1,'']]]
];
