#ifndef FASTLOESS_VERSION_H
#define FASTLOESS_VERSION_H

#define FASTLOESS_CPP_VERSION_MAJOR 3
#define FASTLOESS_CPP_VERSION_MINOR 0
#define FASTLOESS_CPP_VERSION_PATCH 0
#define FASTLOESS_CPP_VERSION_STRING "3.0.0"

#endif