#ifndef FASTLOESS_VERSION_H
#define FASTLOESS_VERSION_H

#define FASTLOESS_CPP_VERSION_MAJOR 2
#define FASTLOESS_CPP_VERSION_MINOR 1
#define FASTLOESS_CPP_VERSION_PATCH 0
#define FASTLOESS_CPP_VERSION_STRING "2.1.0"

#endif