#!/usr/bin/env python3
"""
Plot validation and visualization outputs for fastLoess.
"""

import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

def plot_fraction_comparison():
    path = Path("output/visual/fraction_comparison.csv")
    if not path.exists(): return
    
    df = pd.read_csv(path)
    plt.figure(figsize=(10, 6))
    plt.scatter(df['x'], df['y_noisy'], alpha=0.3, label='Noisy Data', color='gray', s=10)
    plt.plot(df['x'], df['y_true'], 'k--', label='True Signal', alpha=0.8)
    plt.plot(df['x'], df['y_frac_0.2'], label='Fraction 0.2 (Flexible)', linewidth=2)
    plt.plot(df['x'], df['y_frac_0.5'], label='Fraction 0.5 (Balanced)', linewidth=2)
    plt.plot(df['x'], df['y_frac_0.9'], label='Fraction 0.9 (Smooth)', linewidth=2)
    
    plt.title("LOESS Fraction Comparison (Bandwidth Effect)")
    plt.xlabel("X")
    plt.ylabel("Y")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.savefig("output/visual/fraction_comparison.png", dpi=300)
    plt.close()

def plot_intervals_comparison():
    path = Path("output/visual/intervals_comparison.csv")
    if not path.exists(): return
    
    df = pd.read_csv(path)
    plt.figure(figsize=(10, 6))
    plt.scatter(df['x'], df['y_noisy'], alpha=0.3, label='Noisy Data', color='gray', s=10)
    plt.plot(df['x'], df['y_smooth'], 'r-', label='LOESS Fit', linewidth=2)
    
    plt.fill_between(df['x'], df['conf_lower'], df['conf_upper'], color='blue', alpha=0.2, label='95% Confidence Interval')
    plt.fill_between(df['x'], df['pred_lower'], df['pred_upper'], color='green', alpha=0.1, label='95% Prediction Interval')
    
    plt.title("LOESS Intervals (Confidence vs Prediction)")
    plt.xlabel("X")
    plt.ylabel("Y")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.savefig("output/visual/intervals_comparison.png", dpi=300)
    plt.close()

def plot_robustness_comparison():
    path = Path("output/visual/robustness_comparison.csv")
    if not path.exists(): return
    
    df = pd.read_csv(path)
    plt.figure(figsize=(10, 6))
    plt.scatter(df['x'], df['y_noisy'], alpha=0.3, label='Data with Outliers', color='gray', s=15)
    plt.plot(df['x'], df['y_true'], 'k--', label='True Signal', alpha=0.6)
    plt.plot(df['x'], df['y_non_robust'], 'r-', label='Non-Robust (0 iters)', linewidth=1.5, alpha=0.7)
    plt.plot(df['x'], df['y_robust'], 'g-', label='Robust (6 iters)', linewidth=2.5)
    
    plt.title("LOESS Robustness to Outliers")
    plt.xlabel("X")
    plt.ylabel("Y")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.savefig("output/visual/robustness_comparison.png", dpi=300)
    plt.close()

def main():
    print("Generating plots from CSV data...")
    plot_dir = Path("output/visual")
    plot_dir.mkdir(parents=True, exist_ok=True)
    
    plot_fraction_comparison()
    plot_intervals_comparison()
    plot_robustness_comparison()
    # Add more as needed based on CSVs generated by visual.rs
    
    print(f"Plots saved to {plot_dir}/")

if __name__ == "__main__":
    main()
