# Generated by extendr: Do not edit by hand
# nolint start: object_name_linter
#' @usage NULL
#' @useDynLib rfastloess, .registration = TRUE
NULL

RLoess <- new.env(parent = emptyenv())

RLoess$new <- function(
    fraction, iterations, weight_function,
    robustness_method, scaling_method, boundary_policy,
    confidence_intervals, prediction_intervals,
    return_diagnostics, return_residuals,
    return_robustness_weights, return_gradient, zero_weight_fallback,
    auto_converge, cv_fractions, cv_method, cv_k, parallel,
    degree, dimensions, distance_metric,
    weighted_metric_weights,
    surface_mode, return_se, return_sorted,
    cell, interpolation_vertices, boundary_degree_fallback, cv_seed, missing,
    retain_model
) {
    .Call(
        wrap__RLoess__new, fraction, iterations, weight_function,
        robustness_method, scaling_method, boundary_policy,
        confidence_intervals, prediction_intervals, return_diagnostics,
        return_residuals, return_robustness_weights, return_gradient,
        zero_weight_fallback,
        auto_converge, cv_fractions, cv_method, cv_k, parallel,
        degree, dimensions, distance_metric,
        weighted_metric_weights,
        surface_mode, return_se, return_sorted,
        cell, interpolation_vertices, boundary_degree_fallback, cv_seed, missing,
        retain_model
    )
}

RLoess$fit <- function(x, y, custom_weights = NULL) {
    .Call(wrap__RLoess__fit, self, x, y, custom_weights)
}

RLoess$predict <- function(new_x, return_se, confidence_level, prediction_level, return_derivative, extrapolation, max_extrapolation_distance, max_neighbor_distance) {
    .Call(wrap__RLoess__predict, self, new_x, return_se, confidence_level, prediction_level, return_derivative, extrapolation, max_extrapolation_distance, max_neighbor_distance)
}

#' @export
`$.RLoess` <- function(self, name) {
    func <- RLoess[[name]]
    environment(func) <- environment()
    func
}

#' @export
`[[.RLoess` <- `$.RLoess`

RStreamingLoess <- new.env(parent = emptyenv())

RStreamingLoess$new <- function(
    fraction, chunk_size, overlap, iterations,
    weight_function, robustness_method,
    scaling_method, boundary_policy, zero_weight_fallback, auto_converge,
    return_diagnostics, return_residuals, return_robustness_weights,
    return_gradient,
    confidence_intervals, prediction_intervals, return_se,
    merge_strategy, parallel, degree, dimensions,
    distance_metric, weighted_metric_weights, surface_mode,
    cell, interpolation_vertices, boundary_degree_fallback, missing
) {
    .Call(
        wrap__RStreamingLoess__new, fraction, chunk_size, overlap, iterations,
        weight_function, robustness_method, scaling_method,
        boundary_policy, zero_weight_fallback,
        auto_converge, return_diagnostics,
        return_residuals, return_robustness_weights, return_gradient,
        confidence_intervals, prediction_intervals, return_se,
        merge_strategy, parallel,
        degree, dimensions, distance_metric,
        weighted_metric_weights, surface_mode,
        cell, interpolation_vertices, boundary_degree_fallback, missing
    )
}

RStreamingLoess$process_chunk <- function(x, y) {
    .Call(wrap__RStreamingLoess__process_chunk, self, x, y)
}

RStreamingLoess$process_chunk_weighted <- function(x, y, custom_weights) {
    .Call(wrap__RStreamingLoess__process_chunk_weighted, self, x, y, custom_weights)
}

RStreamingLoess$finalize <- function() {
    .Call(wrap__RStreamingLoess__finalize, self)
}

#' @export
`$.RStreamingLoess` <- function(self, name) {
    func <- RStreamingLoess[[name]]
    environment(func) <- environment()
    func
}

#' @export
`[[.RStreamingLoess` <- `$.RStreamingLoess`

ROnlineLoess <- new.env(parent = emptyenv())

ROnlineLoess$new <- function(
    fraction, window_capacity, min_points, iterations,
    weight_function, robustness_method,
    scaling_method, boundary_policy, zero_weight_fallback, update_mode,
    auto_converge, return_robustness_weights, return_gradient,
    confidence_intervals, prediction_intervals, return_se,
    degree, dimensions, distance_metric,
    weighted_metric_weights, surface_mode,
    cell, interpolation_vertices, boundary_degree_fallback, missing
) {
    .Call(
        wrap__ROnlineLoess__new, fraction, window_capacity, min_points,
        iterations, weight_function, robustness_method, scaling_method,
        boundary_policy, zero_weight_fallback, update_mode, auto_converge,
        return_robustness_weights, return_gradient,
        confidence_intervals, prediction_intervals, return_se,
        degree, dimensions, distance_metric,
        weighted_metric_weights, surface_mode,
        cell, interpolation_vertices, boundary_degree_fallback, missing
    )
}

ROnlineLoess$add_point <- function(x, y) {
    .Call(wrap__ROnlineLoess__add_point, self, x, y)
}

ROnlineLoess$add_point_weighted <- function(x, y, weight) {
    .Call(wrap__ROnlineLoess__add_point_weighted, self, x, y, weight)
}

ROnlineLoess$window_diagnostics <- function() {
    .Call(wrap__ROnlineLoess__window_diagnostics, self)
}

ROnlineLoess$predict_window <- function(
    new_x, outputs, confidence_level, prediction_level, extrapolation,
    max_extrapolation_distance, max_neighbor_distance
) {
    .Call(
        wrap__ROnlineLoess__predict_window, self, new_x, outputs,
        confidence_level, prediction_level, extrapolation,
        max_extrapolation_distance, max_neighbor_distance
    )
}

#' @export
`$.ROnlineLoess` <- function(self, name) {
    func <- ROnlineLoess[[name]]
    environment(func) <- environment()
    func
}

#' @export
`[[.ROnlineLoess` <- `$.ROnlineLoess`

# nolint end
