# Generated by extendr: Do not edit by hand
# nolint start: object_name_linter
#' @usage NULL
#' @useDynLib rfastloess, .registration = TRUE
NULL

RLoess <- new.env(parent = emptyenv())

RLoess$new <- function(
    fraction, iterations, delta, weight_function,
    robustness_method, scaling_method, boundary_policy,
    confidence_intervals, prediction_intervals,
    return_diagnostics, return_residuals,
    return_robustness_weights, zero_weight_fallback,
    auto_converge, cv_fractions, cv_method, cv_k, parallel
) {
    .Call(
        wrap__RLoess__new, fraction, iterations, delta, weight_function,
        robustness_method, scaling_method, boundary_policy,
        confidence_intervals, prediction_intervals, return_diagnostics,
        return_residuals, return_robustness_weights, zero_weight_fallback,
        auto_converge, cv_fractions, cv_method, cv_k, parallel
    )
}

RLoess$fit <- function(x, y) .Call(wrap__RLoess__fit, self, x, y)

#' @export
`$.RLoess` <- function(self, name) {
    func <- RLoess[[name]]
    environment(func) <- environment()
    func
}

#' @export
`[[.RLoess` <- `$.RLoess`

RStreamingLoess <- new.env(parent = emptyenv())

RStreamingLoess$new <- function(
    fraction, chunk_size, overlap, iterations,
    delta, weight_function, robustness_method,
    scaling_method, boundary_policy, auto_converge,
    return_diagnostics, return_robustness_weights,
    parallel
) {
    .Call(
        wrap__RStreamingLoess__new, fraction, chunk_size, overlap, iterations,
        delta, weight_function, robustness_method, scaling_method,
        boundary_policy, auto_converge, return_diagnostics,
        return_robustness_weights, parallel
    )
}

RStreamingLoess$process_chunk <- function(x, y) {
    .Call(wrap__RStreamingLoess__process_chunk, self, x, y)
}

RStreamingLoess$finalize <- function() {
    .Call(wrap__RStreamingLoess__finalize, self)
}

#' @export
`$.RStreamingLoess` <- function(self, name) {
    func <- RStreamingLoess[[name]]
    environment(func) <- environment()
    func
}

#' @export
`[[.RStreamingLoess` <- `$.RStreamingLoess`

ROnlineLoess <- new.env(parent = emptyenv())

ROnlineLoess$new <- function(
    fraction, window_capacity, min_points, iterations,
    delta, weight_function, robustness_method,
    scaling_method, boundary_policy, update_mode,
    auto_converge, return_robustness_weights,
    parallel
) {
    .Call(
        wrap__ROnlineLoess__new, fraction, window_capacity, min_points,
        iterations, delta, weight_function, robustness_method, scaling_method,
        boundary_policy, update_mode, auto_converge,
        return_robustness_weights, parallel
    )
}

ROnlineLoess$add_points <- function(x, y) {
    .Call(wrap__ROnlineLoess__add_points, self, x, y)
}

#' @export
`$.ROnlineLoess` <- function(self, name) {
    func <- ROnlineLoess[[name]]
    environment(func) <- environment()
    func
}

#' @export
`[[.ROnlineLoess` <- `$.ROnlineLoess`

# nolint end
