# Generated by extendr: Do not edit by hand
# nolint start: object_name_linter
#' @usage NULL
#' @useDynLib rfastloess, .registration = TRUE
NULL

RLoess <- new.env(parent = emptyenv())

RLoess$new <- function(
    fraction, iterations, weight_function,
    robustness_method, scaling_method, boundary_policy,
    confidence_intervals, prediction_intervals,
    return_diagnostics, return_residuals,
    return_robustness_weights, zero_weight_fallback,
    auto_converge, cv_fractions, cv_method, cv_k, parallel,
    degree, dimensions, distance_metric,
    weighted_metric_weights,
    surface_mode, return_se,
    cell, interpolation_vertices, boundary_degree_fallback, cv_seed
) {
    .Call(
        wrap__RLoess__new, fraction, iterations, weight_function,
        robustness_method, scaling_method, boundary_policy,
        confidence_intervals, prediction_intervals, return_diagnostics,
        return_residuals, return_robustness_weights, zero_weight_fallback,
        auto_converge, cv_fractions, cv_method, cv_k, parallel,
        degree, dimensions, distance_metric,
        weighted_metric_weights,
        surface_mode, return_se,
        cell, interpolation_vertices, boundary_degree_fallback, cv_seed
    )
}

RLoess$fit <- function(x, y, custom_weights = NULL) .Call(wrap__RLoess__fit, self, x, y, custom_weights)

#' @export
`$.RLoess` <- function(self, name) {
    func <- RLoess[[name]]
    environment(func) <- environment()
    func
}

#' @export
`[[.RLoess` <- `$.RLoess`

RStreamingLoess <- new.env(parent = emptyenv())

RStreamingLoess$new <- function(
    fraction, chunk_size, overlap, iterations,
    weight_function, robustness_method,
    scaling_method, boundary_policy, zero_weight_fallback, auto_converge,
    return_diagnostics, return_residuals, return_robustness_weights,
    merge_strategy, parallel, degree, dimensions,
    distance_metric, weighted_metric_weights, surface_mode, return_se,
    confidence_intervals, prediction_intervals,
    cell, interpolation_vertices, boundary_degree_fallback
) {
    .Call(
        wrap__RStreamingLoess__new, fraction, chunk_size, overlap, iterations,
        weight_function, robustness_method, scaling_method,
        boundary_policy, zero_weight_fallback,
        auto_converge, return_diagnostics,
        return_residuals, return_robustness_weights, merge_strategy, parallel,
        degree, dimensions, distance_metric,
        weighted_metric_weights, surface_mode, return_se,
        confidence_intervals, prediction_intervals,
        cell, interpolation_vertices, boundary_degree_fallback
    )
}

RStreamingLoess$process_chunk <- function(x, y) {
    .Call(wrap__RStreamingLoess__process_chunk, self, x, y)
}

RStreamingLoess$finalize <- function() {
    .Call(wrap__RStreamingLoess__finalize, self)
}

#' @export
`$.RStreamingLoess` <- function(self, name) {
    func <- RStreamingLoess[[name]]
    environment(func) <- environment()
    func
}

#' @export
`[[.RStreamingLoess` <- `$.RStreamingLoess`

ROnlineLoess <- new.env(parent = emptyenv())

ROnlineLoess$new <- function(
    fraction, window_capacity, min_points, iterations,
    weight_function, robustness_method,
    scaling_method, boundary_policy, zero_weight_fallback, update_mode,
    auto_converge, return_robustness_weights,
    parallel, degree, dimensions, distance_metric,
    weighted_metric_weights, surface_mode, return_se,
    confidence_intervals, prediction_intervals,
    cell, interpolation_vertices, boundary_degree_fallback
) {
    .Call(
        wrap__ROnlineLoess__new, fraction, window_capacity, min_points,
        iterations, weight_function, robustness_method, scaling_method,
        boundary_policy, zero_weight_fallback, update_mode, auto_converge,
        return_robustness_weights, parallel,
        degree, dimensions, distance_metric,
        weighted_metric_weights, surface_mode, return_se,
        confidence_intervals, prediction_intervals,
        cell, interpolation_vertices, boundary_degree_fallback
    )
}

ROnlineLoess$add_point <- function(x, y) {
    .Call(wrap__ROnlineLoess__add_point, self, x, y)
}

#' @export
`$.ROnlineLoess` <- function(self, name) {
    func <- ROnlineLoess[[name]]
    environment(func) <- environment()
    func
}

#' @export
`[[.ROnlineLoess` <- `$.ROnlineLoess`

# nolint end
